-- Part 4: Lifestyle & Culture + Match-up Battles
-- Final part - run this after part 3

DO $$
DECLARE
    admin_id UUID;
    battle_master_id UUID;
BEGIN
    SELECT id INTO admin_id FROM public.profiles WHERE email = 'admin@verses.app' LIMIT 1;
    SELECT id INTO battle_master_id FROM public.profiles WHERE email = 'battles@verses.app' LIMIT 1;

-- LIFESTYLE & CULTURE RIVALRIES (25 battles)
INSERT INTO public.posts (author_id, type, title, topic, option_a_name, option_a_image, option_b_name, option_b_image) VALUES
(admin_id, 'classic', 'Morning Beverages', 'Breakfast', 'Coffee', 'https://picsum.photos/seed/coffee/600/800', 'Tea', 'https://picsum.photos/seed/tea/600/800'),
(admin_id, 'classic', 'Pet Preferences', 'Pets', 'Dogs', 'https://picsum.photos/seed/dogs/600/800', 'Cats', 'https://picsum.photos/seed/cats/600/800'),
(admin_id, 'classic', 'Vacation Destinations', 'Travel', 'Beach', 'https://picsum.photos/seed/beach/600/800', 'Mountains', 'https://picsum.photos/seed/mountains/600/800'),
(admin_id, 'classic', 'Weather Preferences', 'Climate', 'Summer', 'https://picsum.photos/seed/summer/600/800', 'Winter', 'https://picsum.photos/seed/winter/600/800'),
(admin_id, 'classic', 'Transportation Choice', 'Transport', 'Car', 'https://picsum.photos/seed/car/600/800', 'Public Transit', 'https://picsum.photos/seed/publictransit/600/800'),
(admin_id, 'classic', 'Reading Format', 'Books', 'Physical Books', 'https://picsum.photos/seed/physicalbooks/600/800', 'E-books', 'https://picsum.photos/seed/ebooks/600/800'),
(admin_id, 'classic', 'Exercise Style', 'Fitness', 'Gym Workout', 'https://picsum.photos/seed/gym/600/800', 'Outdoor Running', 'https://picsum.photos/seed/running/600/800'),
(admin_id, 'classic', 'Shopping Method', 'Shopping', 'Online Shopping', 'https://picsum.photos/seed/onlineshopping/600/800', 'In-Store Shopping', 'https://picsum.photos/seed/instoreshop/600/800'),
(admin_id, 'classic', 'Work Style', 'Work', 'Remote Work', 'https://picsum.photos/seed/remotework/600/800', 'Office Work', 'https://picsum.photos/seed/officework/600/800'),
(admin_id, 'classic', 'Communication Style', 'Communication', 'Text Messages', 'https://picsum.photos/seed/texting/600/800', 'Phone Calls', 'https://picsum.photos/seed/phonecalls/600/800'),
(admin_id, 'classic', 'Learning Style', 'Education', 'Visual Learning', 'https://picsum.photos/seed/visuallearn/600/800', 'Audio Learning', 'https://picsum.photos/seed/audiolearn/600/800'),
(admin_id, 'classic', 'Food Delivery', 'Food', 'Cooking at Home', 'https://picsum.photos/seed/cooking/600/800', 'Food Delivery', 'https://picsum.photos/seed/fooddelivery/600/800'),
(admin_id, 'classic', 'Entertainment Format', 'Media', 'Movies', 'https://picsum.photos/seed/movies/600/800', 'TV Series', 'https://picsum.photos/seed/tvseries/600/800'),
(admin_id, 'classic', 'Social Media Usage', 'Social', 'Instagram', 'https://picsum.photos/seed/instagramuse/600/800', 'Twitter', 'https://picsum.photos/seed/twitter/600/800'),
(admin_id, 'classic', 'Music Format', 'Music', 'Streaming', 'https://picsum.photos/seed/musicstreaming/600/800', 'Vinyl Records', 'https://picsum.photos/seed/vinyl/600/800'),
(admin_id, 'classic', 'Payment Method', 'Finance', 'Credit Card', 'https://picsum.photos/seed/creditcard/600/800', 'Cash', 'https://picsum.photos/seed/cash/600/800'),
(admin_id, 'classic', 'Gaming Platform', 'Gaming', 'PC Gaming', 'https://picsum.photos/seed/pcgaming/600/800', 'Console Gaming', 'https://picsum.photos/seed/consolegaming/600/800'),
(admin_id, 'classic', 'Sleep Schedule', 'Lifestyle', 'Early Bird', 'https://picsum.photos/seed/earlybird/600/800', 'Night Owl', 'https://picsum.photos/seed/nightowl/600/800'),
(admin_id, 'classic', 'Photography Style', 'Photography', 'Portrait', 'https://picsum.photos/seed/portrait/600/800', 'Landscape', 'https://picsum.photos/seed/landscape/600/800'),
(admin_id, 'classic', 'Cooking Style', 'Cuisine', 'Italian Food', 'https://picsum.photos/seed/italian/600/800', 'Asian Food', 'https://picsum.photos/seed/asian/600/800'),
(admin_id, 'classic', 'Beverage Choice', 'Drinks', 'Water', 'https://picsum.photos/seed/water/600/800', 'Soda', 'https://picsum.photos/seed/soda/600/800'),
(admin_id, 'classic', 'News Source', 'News', 'Traditional Media', 'https://picsum.photos/seed/traditionalmedia/600/800', 'Social Media News', 'https://picsum.photos/seed/socialnews/600/800'),
(admin_id, 'classic', 'Travel Style', 'Tourism', 'Planned Trips', 'https://picsum.photos/seed/plannedtrips/600/800', 'Spontaneous Travel', 'https://picsum.photos/seed/spontaneous/600/800'),
(admin_id, 'classic', 'Home Style', 'Interior', 'Modern Design', 'https://picsum.photos/seed/modern/600/800', 'Traditional Design', 'https://picsum.photos/seed/traditional/600/800'),
(admin_id, 'classic', 'Investment Choice', 'Investment', 'Stocks', 'https://picsum.photos/seed/stocks/600/800', 'Real Estate', 'https://picsum.photos/seed/realestate/600/800'),

-- MATCH-UP BATTLES (Tournament Style) - 10 battles
(battle_master_id, 'match-up', 'Greatest Sci-Fi Movie Franchise Tournament', 'Movies', 'Star Wars', 'https://picsum.photos/seed/starwars-tournament/600/800', 'Star Trek', 'https://picsum.photos/seed/startrek-tournament/600/800', 
'[{"name": "Blade Runner", "imageUrl": "https://picsum.photos/seed/bladerunner/600/800"}, {"name": "Alien", "imageUrl": "https://picsum.photos/seed/alien/600/800"}, {"name": "The Matrix", "imageUrl": "https://picsum.photos/seed/matrix-tournament/600/800"}, {"name": "Terminator", "imageUrl": "https://picsum.photos/seed/terminator-tournament/600/800"}, {"name": "Dune", "imageUrl": "https://picsum.photos/seed/dune/600/800"}, {"name": "Back to the Future", "imageUrl": "https://picsum.photos/seed/backtofuture/600/800"}]'::jsonb,
'[{"name": "Star Wars", "imageUrl": "https://picsum.photos/seed/starwars-tournament/600/800"}, {"name": "Star Trek", "imageUrl": "https://picsum.photos/seed/startrek-tournament/600/800"}, {"name": "Blade Runner", "imageUrl": "https://picsum.photos/seed/bladerunner/600/800"}, {"name": "Alien", "imageUrl": "https://picsum.photos/seed/alien/600/800"}, {"name": "The Matrix", "imageUrl": "https://picsum.photos/seed/matrix-tournament/600/800"}, {"name": "Terminator", "imageUrl": "https://picsum.photos/seed/terminator-tournament/600/800"}, {"name": "Dune", "imageUrl": "https://picsum.photos/seed/dune/600/800"}, {"name": "Back to the Future", "imageUrl": "https://picsum.photos/seed/backtofuture/600/800"}]'::jsonb),

(battle_master_id, 'match-up', 'Ultimate Marvel Hero Championship', 'Superheroes', 'Iron Man', 'https://picsum.photos/seed/ironman-tournament/600/800', 'Captain America', 'https://picsum.photos/seed/captainamerica-tournament/600/800',
'[{"name": "Thor", "imageUrl": "https://picsum.photos/seed/thor-tournament/600/800"}, {"name": "Hulk", "imageUrl": "https://picsum.photos/seed/hulk-tournament/600/800"}, {"name": "Spider-Man", "imageUrl": "https://picsum.photos/seed/spiderman-tournament/600/800"}, {"name": "Black Widow", "imageUrl": "https://picsum.photos/seed/blackwidow/600/800"}, {"name": "Doctor Strange", "imageUrl": "https://picsum.photos/seed/doctorstrange/600/800"}, {"name": "Black Panther", "imageUrl": "https://picsum.photos/seed/blackpanther/600/800"}]'::jsonb,
'[{"name": "Iron Man", "imageUrl": "https://picsum.photos/seed/ironman-tournament/600/800"}, {"name": "Captain America", "imageUrl": "https://picsum.photos/seed/captainamerica-tournament/600/800"}, {"name": "Thor", "imageUrl": "https://picsum.photos/seed/thor-tournament/600/800"}, {"name": "Hulk", "imageUrl": "https://picsum.photos/seed/hulk-tournament/600/800"}, {"name": "Spider-Man", "imageUrl": "https://picsum.photos/seed/spiderman-tournament/600/800"}, {"name": "Black Widow", "imageUrl": "https://picsum.photos/seed/blackwidow/600/800"}, {"name": "Doctor Strange", "imageUrl": "https://picsum.photos/seed/doctorstrange/600/800"}, {"name": "Black Panther", "imageUrl": "https://picsum.photos/seed/blackpanther/600/800"}]'::jsonb),

(battle_master_id, 'match-up', 'Greatest Rapper of All Time Tournament', 'Hip Hop', 'Tupac', 'https://picsum.photos/seed/tupac-tournament/600/800', 'Biggie', 'https://picsum.photos/seed/biggie-tournament/600/800',
'[{"name": "Jay-Z", "imageUrl": "https://picsum.photos/seed/jayz-tournament/600/800"}, {"name": "Eminem", "imageUrl": "https://picsum.photos/seed/eminem-tournament/600/800"}, {"name": "Nas", "imageUrl": "https://picsum.photos/seed/nas/600/800"}, {"name": "Kendrick Lamar", "imageUrl": "https://picsum.photos/seed/kendrick-tournament/600/800"}, {"name": "Drake", "imageUrl": "https://picsum.photos/seed/drake-tournament/600/800"}, {"name": "Kanye West", "imageUrl": "https://picsum.photos/seed/kanye/600/800"}]'::jsonb,
'[{"name": "Tupac", "imageUrl": "https://picsum.photos/seed/tupac-tournament/600/800"}, {"name": "Biggie", "imageUrl": "https://picsum.photos/seed/biggie-tournament/600/800"}, {"name": "Jay-Z", "imageUrl": "https://picsum.photos/seed/jayz-tournament/600/800"}, {"name": "Eminem", "imageUrl": "https://picsum.photos/seed/eminem-tournament/600/800"}, {"name": "Nas", "imageUrl": "https://picsum.photos/seed/nas/600/800"}, {"name": "Kendrick Lamar", "imageUrl": "https://picsum.photos/seed/kendrick-tournament/600/800"}, {"name": "Drake", "imageUrl": "https://picsum.photos/seed/drake-tournament/600/800"}, {"name": "Kanye West", "imageUrl": "https://picsum.photos/seed/kanye/600/800"}]'::jsonb),

(battle_master_id, 'match-up', 'NBA GOAT Championship', 'Basketball', 'Michael Jordan', 'https://picsum.photos/seed/jordan-tournament/600/800', 'LeBron James', 'https://picsum.photos/seed/lebron-tournament/600/800',
'[{"name": "Kobe Bryant", "imageUrl": "https://picsum.photos/seed/kobe-tournament/600/800"}, {"name": "Magic Johnson", "imageUrl": "https://picsum.photos/seed/magic-tournament/600/800"}, {"name": "Larry Bird", "imageUrl": "https://picsum.photos/seed/bird/600/800"}, {"name": "Shaquille O''Neal", "imageUrl": "https://picsum.photos/seed/shaq-tournament/600/800"}, {"name": "Tim Duncan", "imageUrl": "https://picsum.photos/seed/duncan-tournament/600/800"}, {"name": "Kareem Abdul-Jabbar", "imageUrl": "https://picsum.photos/seed/kareem/600/800"}]'::jsonb,
'[{"name": "Michael Jordan", "imageUrl": "https://picsum.photos/seed/jordan-tournament/600/800"}, {"name": "LeBron James", "imageUrl": "https://picsum.photos/seed/lebron-tournament/600/800"}, {"name": "Kobe Bryant", "imageUrl": "https://picsum.photos/seed/kobe-tournament/600/800"}, {"name": "Magic Johnson", "imageUrl": "https://picsum.photos/seed/magic-tournament/600/800"}, {"name": "Larry Bird", "imageUrl": "https://picsum.photos/seed/bird/600/800"}, {"name": "Shaquille O''Neal", "imageUrl": "https://picsum.photos/seed/shaq-tournament/600/800"}, {"name": "Tim Duncan", "imageUrl": "https://picsum.photos/seed/duncan-tournament/600/800"}, {"name": "Kareem Abdul-Jabbar", "imageUrl": "https://picsum.photos/seed/kareem/600/800"}]'::jsonb),

(battle_master_id, 'match-up', 'Greatest TV Drama Series Tournament', 'Television', 'Breaking Bad', 'https://picsum.photos/seed/breakingbad-tournament/600/800', 'The Sopranos', 'https://picsum.photos/seed/sopranos-tournament/600/800',
'[{"name": "Game of Thrones", "imageUrl": "https://picsum.photos/seed/got/600/800"}, {"name": "The Wire", "imageUrl": "https://picsum.photos/seed/thewire/600/800"}, {"name": "Mad Men", "imageUrl": "https://picsum.photos/seed/madmen/600/800"}, {"name": "Lost", "imageUrl": "https://picsum.photos/seed/lost/600/800"}, {"name": "House of Cards", "imageUrl": "https://picsum.photos/seed/houseofcards/600/800"}, {"name": "Westworld", "imageUrl": "https://picsum.photos/seed/westworld/600/800"}]'::jsonb,
'[{"name": "Breaking Bad", "imageUrl": "https://picsum.photos/seed/breakingbad-tournament/600/800"}, {"name": "The Sopranos", "imageUrl": "https://picsum.photos/seed/sopranos-tournament/600/800"}, {"name": "Game of Thrones", "imageUrl": "https://picsum.photos/seed/got/600/800"}, {"name": "The Wire", "imageUrl": "https://picsum.photos/seed/thewire/600/800"}, {"name": "Mad Men", "imageUrl": "https://picsum.photos/seed/madmen/600/800"}, {"name": "Lost", "imageUrl": "https://picsum.photos/seed/lost/600/800"}, {"name": "House of Cards", "imageUrl": "https://picsum.photos/seed/houseofcards/600/800"}, {"name": "Westworld", "imageUrl": "https://picsum.photos/seed/westworld/600/800"}]'::jsonb);

END $$;
